### ISSUE TITLE
tracker: Rebase onto Fedora 36

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#1101]
# Rebase to a new version of Fedora (N=36)

## At Branching

Branching is when a new stream is "branched" off of `rawhide`. This eventually becomes the next major Fedora (N).

### Release engineering changes

- [x] Verify that a few tags were created when branching occurred:

- `f${N+1}-coreos-signing-pending`
- `f${N+1}-coreos-continuous`

- [x] Add the N+1 signing key short hash (usually found [here](https://pagure.io/fedora-infra/ansible/blob/main/f/roles/bodhi2/backend/templates/pungi.rpm.conf.j2)) to the tag info for the coreos-pool tag. The following commands view the current settings and then update the list to the 32/33/34/35 keys. You'll most likely have to get someone from releng to run the second command (`edit-tag`).
    - `koji taginfo coreos-pool`
    - `koji edit-tag coreos-pool -x tag2distrepo.keys="12c944d0 9570ff31 45719a39 9867c58f"`

### coreos-installer changes

- [x] Update coreos-installer to know about the signing key used for the future new major version of Fedora (N+1).
- [x] Drop the signing key for the obsolete stable release (N-2).

### Update `rawhide` stream

- [x] Update [manifest.yaml](https://github.com/coreos/fedora-coreos-config/blob/rawhide/manifest.yaml) to list N+1 as the releasever.

### Enable `branched` stream

- [x] Update [manifest.yaml](https://github.com/coreos/fedora-coreos-config/blob/branched/manifest.yaml) to list N as the releasever.
- [x] Update [streams.groovy](https://github.com/coreos/fedora-coreos-pipeline/blob/main/streams.groovy) to include the `branched` stream in the list of mechanical refs.

### Update [fedora-coreos-config](https://github.com/coreos/fedora-coreos-config/) `next-devel`

- [x] Bump `releasever` in `manifest.yaml`
- [x] Update the repos in `manifest.yaml` if needed
- [x] Run `cosa fetch --update-lockfile`
- [x] PR the result

### Ship rebased `next`

- [x] Ship `next`
- Set a new update barrier for N-2 on `next`. In the barrier entry set a link to [the docs](https://docs.fedoraproject.org/en-US/fedora-coreos/update-barrier-signing-keys/). See [discussion](https://github.com/coreos/fedora-coreos-tracker/issues/480#issuecomment-631724629).

### Update [fedora-coreos-config](https://github.com/coreos/fedora-coreos-config/) `testing-devel`

- [x] Bump `releasever` in `manifest.yaml`
- [x] Update the repos in `manifest.yaml` if needed
- [x] Run `cosa fetch --update-lockfile`
- [x] Bump the base Fedora version in `ci/buildroot/Dockerfile`
- [x] PR the result

### Ship rebased `testing`

- [x] Ship `testing`
- Set a new update barrier for N-2 on `testing`. In the barrier entry set a link to [the docs](https://docs.fedoraproject.org/en-US/fedora-coreos/update-barrier-signing-keys/). See [discussion](https://github.com/coreos/fedora-coreos-tracker/issues/480#issuecomment-631724629).

### Disabled `branched` stream

- [x] Update [streams.groovy](https://github.com/coreos/fedora-coreos-pipeline/blob/main/streams.groovy) to remove the `branched` stream in the list of mechanical refs.

### Untag old packages

`koji untag` N-2 packages from the pool (at some point we'll have GC in place to do this for us, but for now we must remember to do this manually or otherwise distRepo will fail once the signed packages are GC'ed). For example the following snippet finds all RPMs signed by the Fedora 32 key and untags them. Use this process:

- [x] Find the key short hash. Usually found [here](https://pagure.io/fedora-infra/ansible/blob/main/f/roles/bodhi2/backend/templates/pungi.rpm.conf.j2). Then:

```
f32key=12c944d0
key=$f32key
untaglist=''
for build in $(koji list-tagged --quiet coreos-pool | cut -f1 -d' '); do
    if koji buildinfo $build | grep $key 1>/dev/null; then
        untaglist+="${build} "
        echo "Adding $build to untag list"
    fi
done
```

- [x] Now we have a list of builds to untag. But we need one more sanity check. Let's make sure none of those are actually being used. Fire up the latest FCOS `testing-devel` and run:

```
f32key=12c944d0
key=$f32key
rpm -qai | grep -B 8 $key
```

If there are any RPMs signed by the old key they'll need to be investigated. Maybe they shouldn't be used any longer. Or maybe they're still needed.

- [x] After verifying the list looks good:

```
koji untag-build coreos-pool $untaglist
```

- [x] Now that untagging is done, give a heads up to rpm-ostree developers that N-2 packages have been untagged and that they may need to update their CI compose tests to freeze on a newer FCOS commit.

- [x] Remove the N-2 signing key from the tag info for the coreos-pool tag. The following commands view the current settings and then update the list to the 33/34/35 keys. You'll most likely have to get someone from releng to run the second command (`edit-tag`).
    - `koji taginfo coreos-pool`
    - `koji edit-tag coreos-pool -x tag2distrepo.keys="9570ff31 45719a39 9867c58f"`

### Disable `next-devel` stream

We prefer to disable `next-devel` when there is no difference between `testing-devel` and `next-devel`. This allows us to prevent wasting a bunch of resources (bandwidth, storage, compute) for no reason. After the switch to N if `next-devel` and `testing-devel` are in lockstep, then disable `next-devel`.

- [x] Follow the instructions [here](https://github.com/coreos/fedora-coreos-pipeline/tree/main/next-devel) to disable `next-devel`

### Ship rebased `stable`

- [x] Ship `stable`
- Set a new update barrier for N-2 on `stable`. In the barrier entry set a link to [the docs](https://docs.fedoraproject.org/en-US/fedora-coreos/update-barrier-signing-keys/). See [discussion](https://github.com/coreos/fedora-coreos-tracker/issues/480#issuecomment-631724629).

## Miscellaneous container updates

These are various containers in use throughout our ecosystem. We should update or open a ticket to track updating them once a new Fedora release is out. If you open a ticket instead of doing the update add a link to the ticket as comment.

- [x] Update coreos-assembler or open ticket to update:
    - [Dockerfile](https://github.com/coreos/coreos-assembler/blob/main/Dockerfile)
- [x] Update coreos-installer
    - [Dockerfile](https://github.com/coreos/coreos-installer/blob/main/Dockerfile)
- [x] Update Ignition
    - [Dockerfile.validate](https://github.com/coreos/ignition/blob/main/Dockerfile.validate)
- [x] Update Butane
    - [Dockerfile](https://github.com/coreos/butane/blob/main/Dockerfile)
- [x] Update fedora-coreos-cincinnati
    - [Dockerfile](https://github.com/coreos/fedora-coreos-cincinnati/blob/main/dist/fedora-infra/Dockerfile)
- [x] Update config-bot
    - [Dockerfile](https://github.com/coreos/fedora-coreos-releng-automation/blob/main/config-bot/Dockerfile)
- [x] Update coreos-koji-tagger
    - [Dockerfile](https://github.com/coreos/fedora-coreos-releng-automation/blob/main/coreos-koji-tagger/Dockerfile)
    - [ImageStream](https://pagure.io/fedora-infra/ansible/blob/main/f/roles/openshift-apps/coreos-koji-tagger/templates/imagestream.yml)
    - [BuildConfig](https://pagure.io/fedora-infra/ansible/blob/main/f/roles/openshift-apps/coreos-koji-tagger/templates/buildconfig.yml)
- [x] Update coreos-ostree-importer
    - [Dockerfile](https://github.com/coreos/fedora-coreos-releng-automation/blob/main/coreos-ostree-importer/Dockerfile)
    - [ImageStream](https://pagure.io/fedora-infra/ansible/blob/main/f/roles/openshift-apps/coreos-ostree-importer/templates/imagestream.yml)
    - [BuildConfig](https://pagure.io/fedora-infra/ansible/blob/main/f/roles/openshift-apps/coreos-ostree-importer/templates/buildconfig.yml)

**Comment by dustymabe** [comment]
request for releng to add the f37 signing key to the taginfo for `coreos-pool`: https://pagure.io/releng/issue/10635

**Comment by dustymabe** [comment]
- https://github.com/coreos/coreos-installer/pull/770

**Comment by dustymabe** [comment]
- https://github.com/coreos/fedora-coreos-config/pull/1506
- https://github.com/coreos/fedora-coreos-config/pull/1507

**Comment by dustymabe** [comment]
- https://github.com/coreos/fedora-coreos-pipeline/pull/476

**Comment by dustymabe** [comment]
- https://github.com/coreos/fedora-coreos-config/pull/1605

**Comment by dustymabe** [comment]
In general you may see us fast-tracking packages in `next-devel` before they reach bodhi stable. In general this is to prevent downgrades (newer packages in f35 than in f36) when comparing `testing*` streams to `next*` streams.

**Comment by dustymabe** [comment]
Just noting we updated the release barrier for `next` in https://github.com/coreos/fedora-coreos-streams/commit/40fde3e66f10d6b7ec2ae656d77c1dfe7a55ce15

**Comment by lucab** [comment]
For coreos-cincinnati, we are artificially keeping it on an older Fedora base image due to https://pagure.io/fedora-infrastructure/issue/10111. I crossed it out for now.

**Comment by dustymabe** [comment]
> For coreos-cincinnati, we are artificially keeping it on an older Fedora base image due to https://pagure.io/fedora-infrastructure/issue/10111. I crossed it out for now.

Hmm. We're migrating to a new (OCP4) cluster, though. Doesn't that mean the issue goes away?

**Comment by lucab** [comment]
At least not until we have migrated out of the old OCP3 cluster, which won't happen before F36 GA due to the infra freeze.
At that point, yes I hope the issue will be solved and we'll be able to update the base image.

**Comment by bgilbert** [comment]
Dockerfile updates:
- https://github.com/coreos/ignition/pull/1364
- https://github.com/coreos/coreos-installer/pull/857
- https://github.com/coreos/butane/pull/345

**Comment by dustymabe** [comment]
- PR to switch `testing-devel`
    - https://github.com/coreos/fedora-coreos-config/pull/1732

**Comment by dustymabe** [comment]
- https://github.com/coreos/fedora-coreos-pipeline/pull/522

**Comment by dustymabe** [comment]
- https://github.com/coreos/coreos-assembler/pull/2856

**Comment by lucab** [comment]
https://github.com/coreos/fedora-coreos-cincinnati/pull/65

**Comment by dustymabe** [comment]
- https://github.com/coreos/fedora-coreos-releng-automation/pull/152

**Comment by dustymabe** [comment]
I'm going through and untagging F34 packages from `coreos-pool` today.

**Comment by dustymabe** [comment]
- https://github.com/coreos/fedora-coreos-config/pull/1752

**Comment by lucab** [comment]
We had to revert the F36 bump for `fedora-coreos-cincinnati` as it was causing service disruption. We will attempt it again, and we are running on F35 for the moment. The ticket for this is https://github.com/coreos/fedora-coreos-cincinnati/issues/70.

**Comment by dustymabe** [comment]
Closing this out since we've already shipped F37 and completed all tasks.
