### ISSUE TITLE
F36 FCOS Test Day TODO List

### ISSUE THREAD

**Issue by miabbott** [coreos/fedora-coreos-tracker#1147]
## Create New Documentation

Create a PR for each of these items on https://github.com/coreos/fedora-coreos-docs/

- [ ] Installing FCOS on Azure Stack under Provisioning section
    - @mike-nguyen
- [x] Installing FCOS on Nutanix under Provisioning section
    - @sohankunkerkar
- [x] Enabling `kdump` via Ignition under System Configuration section
    - @mike-nguyen 

## Create New Test Cases

1. ensure you are authenticated with the [Fedora Account System](https://accounts.fedoraproject.org/)
2. create a new [Fedora Wiki page](https://fedoraproject.org/wiki/Fedora_Project_Wiki) for the test case
   * try to follow the existing naming convention + categorization when creating new page: `QA:Testcase_CoreOS_<test_case>`
   * example: `https://fedoraproject.org/wiki/QA:Testcase_CoreOS_complex_partitioning`
   * confirm that `[[Category:CoreOS Test Cases]]` is present at the bottom of the new wiki page
3. link the newly created wiki page on the [test day wiki page](https://fedoraproject.org/wiki/Test_Day:Fedora_36_CoreOS_Test_Day_TestdayApp_Metadata)

- [ ] provisioning on Azure Stack (requires new docs from above list)
    - @mike-nguyen
- [ ] provisioning on Nutanix (requires new docs from above list)
    - @aaradhak
- [ ] provisioning on [Raspberry Pi 4 using U-Boot and EDK2](https://docs.fedoraproject.org/en-US/fedora-coreos/provisioning-raspberry-pi4/)
    - @davdunc
- [x] provisioning on [Vultr](https://docs.fedoraproject.org/en-US/fedora-coreos/provisioning-vultr/)
    - @dustymabe
        - [Test Case](https://fedoraproject.org/wiki/QA:Testcase_CoreOS_Provisioning_on_Vultr)
        - [Docs Update](https://github.com/coreos/fedora-coreos-docs/pull/383) 
- [x] [customizing NIC name](https://docs.fedoraproject.org/en-US/fedora-coreos/customize-nic/)
    - @jlebon
- [x] configuring [SwapOnZRam](https://docs.fedoraproject.org/en-US/fedora-coreos/sysconfig-configure-swaponzram/)
    - @fifofonix
        - [Test Case](https://fedoraproject.org/wiki/QA:Testcase_swap_on_zram)
- [ ] configuring [WireGuard](https://docs.fedoraproject.org/en-US/fedora-coreos/sysconfig-configure-wireguard/)
    - @dustymabe
- [x] [setting alternatives](https://docs.fedoraproject.org/en-US/fedora-coreos/alternatives/)
    - @jlebon
- [x] [node counting](https://docs.fedoraproject.org/en-US/fedora-coreos/counting/)
    - @jlebon
- [x] configuring [Time Zone](https://docs.fedoraproject.org/en-US/fedora-coreos/time-zone/)
    - @dustymabe
        - [Test Case](https://fedoraproject.org/wiki/QA:Testcase_time_zone) 
- [x] configuring `kdump` via Ignition (requires new docs from above list)
    - @mike-nguyen
- [x] [debugging kernel crashes](https://docs.fedoraproject.org/en-US/fedora-coreos/debugging-kernel-crashes/)
    - @ravanelli 
- [x] [debugging with toolbx](https://docs.fedoraproject.org/en-US/fedora-coreos/debugging-with-toolbox/)
    - @aaradhak
- [ ] [enabling autologin and custom hostname tutorial](https://docs.fedoraproject.org/en-US/fedora-coreos/tutorial-autologin/)
    - @davdunc
- [ ] [starting a service on first boot tutorial](https://docs.fedoraproject.org/en-US/fedora-coreos/tutorial-services/)
    - @davdunc
- [ ] [SSH access and starting containers tutorial](https://docs.fedoraproject.org/en-US/fedora-coreos/tutorial-containers/)
    - @davdunc
- [ ] [Launching a user-level systemd unit on boot tutorial](https://docs.fedoraproject.org/en-US/fedora-coreos/tutorial-user-systemd-unit-on-boot/)
    - @davdunc
- [ ] [Testing FCOS updates tutorial](https://docs.fedoraproject.org/en-US/fedora-coreos/tutorial-updates/)
    - @davdunc

**Comment by dustymabe** [comment]
We discussed this in the [community meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/72W3BPKTCILRLKLJ4GOXQO2S5WXQQZ34/).

Lot's of volunteers stepped up. I'll update the description above.

**Comment by dustymabe** [comment]
Closing this out since it's unlikely anyone is still working on this.
