### ISSUE TITLE
tracker: F37 Test Day

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#1225]
## Initial Tasks (to be done at least one week before test week)

- [x] Open this ticket in the `fedora-coreos-tracker` repo
- [x] Open a ticket with [Fedora QA](https://pagure.io/fedora-qa/issues).
  - [F36 example](https://pagure.io/fedora-qa/issue/695)

To be done after the Fedora QA folks have taken action on the QA ticket:

- [x] Confirm the Test Day page is created on the Fedora Wiki.
  - For example: <https://fedoraproject.org/wiki/Test_Day:Fedora_36_CoreOS_2022-04-04>
- [x] Confirm the Test Day results app is created.
  - For example: <https://testdays.fedoraproject.org/events/131>
- [x] Choose a day during the Test Week to host a video session for live debug help
- [x] Setup a Google Meet or other video conference session
- [x] Create a HackMD doc for capturing notes during live video session
- [ ] Find volunteers to enumerate new documentation + test cases required for Test Week
  - Best done via dedicated video session
- [ ] File an issue on `fedora-coreos-tracker` with TODO items.
  - For example: <https://github.com/coreos/fedora-coreos-tracker/issues/1147>
- [x] File a ticket requesting a Fedora badge is created
  - For example: <https://pagure.io/fedora-badges/issue/871>

## Announcing Test Week

Should be completed after the Initial Tasks are done

- [x] Draft an email to <coreos@lists.fedoraproject.org> announcing the Test Week
  - [x] Include a link to the Fedora Wiki
  - [x] Include a link to the Test Day results app
  - [x] Include a link to `fedora-coreos-tracker` for Test Week
  - [x] Include a link to the video conference
  - [x] Include a link to the HackMD doc
- [x] Cross-post announcement email to discussion.fedoraproject.org with `#coreos` tag

- Example format: <https://hackmd.io/lCrVoW_RSMCRf2neiGhiPg>

## During Test Week

- Monitor `fedora-coreos-tracker` for new issues reported as part of Test Week
- Monitor #fedora-coreos on IRC for new issues reported as part of Test Week
- Ensure there is one or more representatives of Fedora CoreOS team present for live video session

## After Test Week

- [ ] Update `fedora-coreos-tracker` ticket with any issues found
- [ ] Update `fedora-coreos-tracker` ticket with any documentation updates made
- [ ] Review Test Day results app and follow-up on any errors reported, if possible
- [ ] Follow up with the Fedora Badges ticket with Fedora Account System (FAS) usernames that participated in Test Week

**Comment by dustymabe** [comment]
I talked with Sumantro and we're going to target Thursday `09/22/22` for the F37 CoreOS Test day this cycle.

**Comment by jasonbrooks** [comment]
I opened the Fedora QA ticket: https://pagure.io/fedora-qa/issue/712

**Comment by dustymabe** [comment]
We discussed this at the [community meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/TI3MVNNEXLHCEZV3PKPOGSAIFQSQ5AME/).

@jasonbrooks has stepped up and is going to help us organize this test day. Thank you @jasonbrooks!

**Comment by jasonbrooks** [comment]
@sumantro93 I believe we need action on our Fedora QA ticket to proceed with our checklist steps?

**Comment by jasonbrooks** [comment]
test day page and results app created:

https://testdays.fedoraproject.org/events/143
http://fedoraproject.org/wiki/Test_Day:Fedora_37_CoreOS_2022-09-22

**Comment by jasonbrooks** [comment]
FCOS 37 Test Day Live Debug Session
Thursday, September 22
Google Meet joining info
Video call link: https://meet.google.com/dsb-wixf-kqk
Or dial: ‪(US) +1 413-561-7664‬ PIN: ‪291 773 689‬#
More phone numbers: https://tel.meet/dsb-wixf-kqk?pin=2093097800113
Or join via SIP: sip:2093097800113@gmeet.redhat.com

**Comment by dustymabe** [comment]
Discussion Forum Post: https://discussion.fedoraproject.org/t/fedora-37-fedora-coreos-test-day-today/42798

**Comment by jasonbrooks** [comment]
request test day badge: https://pagure.io/fedora-badges/issue/890

**Comment by travier** [comment]
We are now moving to F42. Closing this one.
