### ISSUE TITLE
Tracker for switching to chunked ostree container images

### ISSUE THREAD

**Issue by cgwalters** [coreos/fedora-coreos-tracker#1226]
https://github.com/ostreedev/ostree-rs-ext/issues/69 has been shipped in the ostree stack for quite a while.  However, us actually making use of it turned out to block on dealing with how we inject GPG signatures, which was fixed in https://github.com/ostreedev/ostree-rs-ext/pull/301

But that isn't in an rpm-ostree release yet, so I made `registry.ci.openshift.org/coreos/coreos-assembler:continuous` which has rpm-ostree from git.

Then we just landed https://github.com/coreos/coreos-assembler/pull/2902 in coreos-assembler, so along with https://github.com/coreos/fedora-coreos-config/pull/1698 for rawhide, I manually kicked off a force build job: https://jenkins-fedora-coreos-pipeline.apps.ocp.fedoraproject.org/job/build/746/console

After this:

- [ ] Some sanity checking that e.g. existing FCOS stable can `rpm-ostree rebase --experimental ostree-remote-registry:fedora:quay.io/coreos-assembler/fcos:rawhide`
- [ ] Verify that podman builds work with it
- [ ] Get rpm-ostree released with this fix
- [ ] Wait until coreos-assembler picks it up
- [ ] Update the code changed by https://github.com/coreos/coreos-assembler/commit/de628bc6d86fcea34b89b3cb3f019a78b0f40384 to hard require the new API
- [ ] Switch all FCOS streams to `oci-chunked`
- [ ] Profit

**Comment by cgwalters** [comment]
Update: https://jenkins-fedora-coreos-pipeline.apps.ocp.fedoraproject.org/job/build/751/console succeed!

`quay.io/coreos-assembler/fcos:rawhide` is now a chunked image.

**Comment by cgwalters** [comment]
OK this now blocks on https://github.com/ostreedev/ostree-rs-ext/issues/309

**Comment by cgwalters** [comment]
This is done!
