### ISSUE TITLE
tracker: Rebase onto Fedora 38

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#1356]
# Rebase to a new version of Fedora (N=38)

### Open tickets to track related work for this release

- [x] Fedora Changes Considerations ([example](https://github.com/coreos/fedora-coreos-tracker/issues/1222)): https://github.com/coreos/fedora-coreos-tracker/issues/1357
- [x] Package Additions/Removals ([example](https://github.com/coreos/fedora-coreos-tracker/issues/1221)) https://github.com/coreos/fedora-coreos-tracker/issues/1435
- [x] Test Week ([template](https://github.com/coreos/fedora-coreos-tracker/issues/new?template=test-week.md&title=tracker:+FN+Test+Week)) https://github.com/coreos/fedora-coreos-tracker/issues/1440

## At Branching

Branching is when a new stream is "branched" off of `rawhide`. This eventually becomes the next major Fedora (N).

### Release engineering changes

- [x] Verify that a few tags were created when branching occurred:

- `f${N+1}-coreos-signing-pending`
- `f${N+1}-coreos-continuous`

- [x] Add and tag a package (any package) which is in the stable repos into the continuous tag. This will create the initial yum repo that's used as input for building the COSA container.

- `koji add-pkg --owner ${FAS_USERNAME} f${N+1}-coreos-continuous $PKG`
    - example: `koji add-pkg --owner dustymabe f36-coreos-continuous fedora-release`
    - This example uses the [`fedora-release`](https://src.fedoraproject.org/rpms/fedora-release) RPM, but it could be any other.
- `koji tag-build f${N+1}-coreos-continuous $BUILD`
    - example: `koji tag-build f36-coreos-continuous fedora-release-36-0.16`

- [x] Add the N+1 signing key short hash (usually found [here](https://pagure.io/fedora-infra/ansible/blob/main/f/roles/bodhi2/backend/templates/pungi.rpm.conf.j2)) to the tag info for the coreos-pool tag. The following commands view the current settings and then update the list to the 32/33/34/35 keys. You'll most likely have to get someone from releng to run the second command (`edit-tag`).
    - `koji taginfo coreos-pool`
    - `koji edit-tag coreos-pool -x tag2distrepo.keys="12c944d0 9570ff31 45719a39 9867c58f"`

### coreos-installer changes

- [x] Update coreos-installer to know about the signing key used for the future new major version of Fedora (N+1).
- [x] Drop the signing key for the obsolete stable release (N-2).

### Update `rawhide` stream

- [x] Update [manifest.yaml](https://github.com/coreos/fedora-coreos-config/blob/rawhide/manifest.yaml) to list N+1 as the releasever.

### Enable `branched` stream

- [x] Update [manifest.yaml](https://github.com/coreos/fedora-coreos-config/blob/branched/manifest.yaml) to list N as the releasever.
- [x] Update [config.yaml](https://github.com/coreos/fedora-coreos-pipeline/blob/main/config.yaml) to un-comment out the `branched` stream definition.

### Update [fedora-coreos-config](https://github.com/coreos/fedora-coreos-config/) `next-devel`

- [x] Bump `releasever` in `manifest.yaml`
- [x] Update the repos in `manifest.yaml` if needed
- [x] Run `cosa fetch --dry-run --update-lockfile`
    - this updates the x86_64 lockfile - the others will get updated when `bump-lockfile` runs.
    - in the future we may support [this](https://github.com/coreos/coreos-assembler/issues/3088) in `cosa fetch` directly
- [x] PR the result

- [x] Re-enable `next-devel` if needed ([docs](https://github.com/coreos/fedora-coreos-pipeline/tree/main/next-devel))
- [x] Disable `branched` stream since it is no longer needed.
    - Update [config.yaml](https://github.com/coreos/fedora-coreos-pipeline/blob/main/config.yaml) to comment out the `branched` stream definition.

### Ship rebased `next`

- [x] Ship `next`
- [x] Set a new update barrier for the final release of N-1 on `next`. In the barrier entry set a link to [the docs](https://docs.fedoraproject.org/en-US/fedora-coreos/update-barrier-signing-keys/). See [discussion](https://github.com/coreos/fedora-coreos-tracker/issues/480#issuecomment-1247314065)

### Update [fedora-coreos-config](https://github.com/coreos/fedora-coreos-config/) `testing-devel`

- [x] Bump `releasever` in `manifest.yaml`
- [x] Update the repos in `manifest.yaml` if needed
- [x] Sync the lockfiles for all arches from `next-devel`
- [x] Bump the base Fedora version in `ci/buildroot/Dockerfile`
- [x] PR the result

### Ship rebased `testing`

- [x] Ship `testing`
- [x] Set a new update barrier for the final release of N-1 on `testing`. In the barrier entry set a link to [the docs](https://docs.fedoraproject.org/en-US/fedora-coreos/update-barrier-signing-keys/). See [discussion](https://github.com/coreos/fedora-coreos-tracker/issues/480#issuecomment-1247314065)

### Disable `branched` stream

- [x] Update [streams.groovy](https://github.com/coreos/fedora-coreos-pipeline/blob/main/streams.groovy) to remove the `branched` stream in the list of mechanical refs.

### Untag old packages

`koji untag` N-2 packages from the pool (at some point we'll have GC in place to do this for us, but for now we must remember to do this manually or otherwise distRepo will fail once the signed packages are GC'ed). For example the following snippet finds all RPMs signed by the Fedora 32 key and untags them. Use this process:

- [x] Find the key short hash. Usually found [here](https://pagure.io/fedora-infra/ansible/blob/main/f/roles/bodhi2/backend/templates/pungi.rpm.conf.j2). Then:

```
f32key=12c944d0
key=$f32key
echo > untaglist # create or empty out file
for build in $(koji list-tagged --quiet coreos-pool | cut -f1 -d' '); do
    if koji buildinfo $build | grep $key 1>/dev/null; then
        echo "Adding $build to untag list"
        echo "${build}" >> untaglist
    fi
done
```

Now we have a list of builds to untag. But we need a few more sanity checks.

- [x] Make sure none of the builds are used in `N` based FCOS. Check by running:

```
f32key=12c944d0
key=$f32key
podman run -it --rm quay.io/fedora/fedora-coreos:testing-devel rpm -qai | grep -B 9 $key
podman rmi quay.io/fedora/fedora-coreos:testing-devel
```

If there are any RPMs signed by the old key they'll need to be investigated. Maybe they shouldn't be used any longer. Or maybe they're still needed.

- [x] For any RPMS still used by `N-1` based FCOS let's remove them from the untaglist. Check by running:

```
f32key=12c944d0
key=$f32key
podman run -it --rm quay.io/fedora/fedora-coreos:stable rpm -qai | grep -B 9 $key
podman rmi quay.io/fedora/fedora-coreos:stable
```

NOTE: This assumes `stable` is still on `N-1`.

Remove any entries from the `untaglist` file that are still being used.

- [x] After verifying the list looks good, untag:

```
# use xargs so we don't exhaust bash string limit
cat untaglist | xargs -L50 koji untag-build coreos-pool
```

- [x] Now that untagging is done, give a heads up to rpm-ostree developers that N-2 packages have been untagged and that they may need to update their CI compose tests to freeze on a newer FCOS commit.

- [x] Remove the N-2 signing key from the tag info for the coreos-pool tag. The following commands view the current settings and then update the list to the 33/34/35 keys. You'll most likely have to get someone from releng to run the second command (`edit-tag`).
    - `koji taginfo coreos-pool`
    - `koji edit-tag coreos-pool -x tag2distrepo.keys="9570ff31 45719a39 9867c58f"`

### Disable `next-devel` stream

We prefer to disable `next-devel` when there is no difference between `testing-devel` and `next-devel`. This allows us to prevent wasting a bunch of resources (bandwidth, storage, compute) for no reason. After the switch to N if `next-devel` and `testing-devel` are in lockstep, then disable `next-devel`.

- [x] Follow the instructions [here](https://github.com/coreos/fedora-coreos-pipeline/tree/main/next-devel) to disable `next-devel`

### Switch upstream packages to shipping release binaries from Fedora (N)

- [x] Update [repo-templates](https://github.com/coreos/repo-templates) [config.yaml](https://github.com/coreos/repo-templates/blob/main/config.yaml) with the version number and GPG key ID for Fedora (N).

### Ship rebased `stable`

- [x] Ship `stable`
- [x] Set a new update barrier for the final release of N-1 on `stable`. In the barrier entry set a link to [the docs](https://docs.fedoraproject.org/en-US/fedora-coreos/update-barrier-signing-keys/). See [discussion](https://github.com/coreos/fedora-coreos-tracker/issues/480#issuecomment-1247314065)

### Open ticket for the next Fedora rebase

- [x] Create a new ticket from the [rebase template](https://github.com/coreos/fedora-coreos-tracker/issues/new?assignees=&labels=area%2Fplatforms%2C+kind%2Fenhancement&template=rebase.md&title=tracker:+Rebase+onto+Fedora+N)
    - label with `FN` label where `N` is the Fedora version.

## Miscellaneous container updates

These are various containers in use throughout our ecosystem. We should update or open a ticket to track updating them once a new Fedora release is out. If you open a ticket instead of doing the update add a link to the ticket as comment.

- [x] Update coreos-assembler or open ticket to update:
    - [Dockerfile](https://github.com/coreos/coreos-assembler/blob/main/Dockerfile)
- [x] Update coreos-installer - https://github.com/coreos/coreos-installer/pull/1167
    - [Dockerfile](https://github.com/coreos/coreos-installer/blob/main/Dockerfile)
- [x] Update Ignition - https://github.com/coreos/ignition/pull/1611
    - [Dockerfile.validate](https://github.com/coreos/ignition/blob/main/Dockerfile.validate)
- [x] Update Butane - https://github.com/coreos/butane/pull/459
    - [Dockerfile](https://github.com/coreos/butane/blob/main/Dockerfile)
- [ ] Update fedora-coreos-cincinnati
    - [Dockerfile](https://github.com/coreos/fedora-coreos-cincinnati/blob/main/dist/fedora-infra/Dockerfile)
- [ ] Update config-bot
    - [Dockerfile](https://github.com/coreos/fedora-coreos-releng-automation/blob/main/config-bot/Dockerfile)
- [ ] Update coreos-koji-tagger
    - [Dockerfile](https://github.com/coreos/fedora-coreos-releng-automation/blob/main/coreos-koji-tagger/Dockerfile)
    - [ImageStream](https://pagure.io/fedora-infra/ansible/blob/main/f/roles/openshift-apps/coreos-koji-tagger/templates/imagestream.yml)
    - [BuildConfig](https://pagure.io/fedora-infra/ansible/blob/main/f/roles/openshift-apps/coreos-koji-tagger/templates/buildconfig.yml)
- [ ] Update coreos-ostree-importer
    - [Dockerfile](https://github.com/coreos/fedora-coreos-releng-automation/blob/main/coreos-ostree-importer/Dockerfile)
    - [ImageStream](https://pagure.io/fedora-infra/ansible/blob/main/f/roles/openshift-apps/coreos-ostree-importer/templates/imagestream.yml)
    - [BuildConfig](https://pagure.io/fedora-infra/ansible/blob/main/f/roles/openshift-apps/coreos-ostree-importer/templates/buildconfig.yml)

**Comment by dustymabe** [comment]
- https://github.com/coreos/fedora-coreos-tracker/issues/1357

**Comment by jlebon** [comment]
When updating `testing-devel` to f38, remember to drop these entries from `kola-denylist.yaml`: https://github.com/coreos/fedora-coreos-config/blob/1a37a6ec05e7f611b5d4acf343c35ea51bc4d35a/kola-denylist.yaml#L20-L39

**Comment by aaradhak** [comment]
[add Fedora 39 signing key to coreos-pool tag](https://pagure.io/releng/issue/11287)

**Comment by aaradhak** [comment]
https://github.com/coreos/coreos-installer/pull/1113

**Comment by aaradhak** [comment]
- https://github.com/coreos/fedora-coreos-config/pull/2246

**Comment by aaradhak** [comment]
- https://github.com/coreos/fedora-coreos-pipeline/pull/817

**Comment by aaradhak** [comment]
- https://github.com/coreos/fedora-coreos-config/pull/2254

**Comment by aaradhak** [comment]
- https://github.com/coreos/fedora-coreos-pipeline/pull/830

**Comment by jlebon** [comment]
coreos-status email: https://hackmd.io/aw7c1xNLRNSxcomW63Carw

**Comment by dustymabe** [comment]
> * Set a new update barrier for the final release of N-1 on `next`. In the barrier entry set a link to [the docs](https://docs.fedoraproject.org/en-US/fedora-coreos/update-barrier-signing-keys/). See [discussion](https://github.com/coreos/fedora-coreos-tracker/issues/480#issuecomment-1247314065)

The last release of f37 is a barrier, but the link won't be to the signing key issue because there was another reason to do it that way.

**Comment by dustymabe** [comment]
Fedora 38 is a Go for Tuesday April 18th.

The only package that we need that isn't currently in `next-devel` is [`fuse3-3.13.1-2.fc38`](https://bodhi.fedoraproject.org/updates/FEDORA-2023-37e142ea83) (part of [this](https://pagure.io/releng/issue/11306#comment-851442) push) so I'll fast-track that to get a `next-devel` build sooner.

**Comment by dustymabe** [comment]
- https://github.com/coreos/fedora-coreos-config/pull/2376

**Comment by dustymabe** [comment]
- https://github.com/coreos/fedora-coreos-pipeline/pull/858

**Comment by dustymabe** [comment]
The fix for this went into `testing` stream release `38.20230414.2.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
For the "Set a new update barrier for the final release of N-1 on $STREAM" we'll let the update barriers that we put in place for https://github.com/coreos/fedora-coreos-tracker/issues/1441 suffice here.

- https://github.com/coreos/fedora-coreos-streams/pull/671
- https://github.com/coreos/fedora-coreos-streams/pull/676
- https://github.com/coreos/fedora-coreos-streams/pull/682

**Comment by dustymabe** [comment]
stable was switched over in: https://github.com/coreos/fedora-coreos-config/commit/4524c7d6565632a7b3d9b3705db230339793029b

**Comment by dustymabe** [comment]
- https://github.com/coreos/repo-templates/pull/110

**Comment by dustymabe** [comment]
The fix for this went into `stable` stream release `38.20230414.3.0`.

**Comment by dustymabe** [comment]
- https://github.com/coreos/coreos-assembler/pull/3451

**Comment by jlebon** [comment]
The only steps remaining in this one are the container updates, which have now been superseded by Fedora 39. Tracked at https://github.com/coreos/fedora-coreos-tracker/issues/1490.
