### ISSUE TITLE
F38 FCOS Test Day TODO List

### ISSUE THREAD

**Issue by ravanelli** [coreos/fedora-coreos-tracker#1445]
## Existing test cases

 * https://testdays.fedoraproject.org/events/153

## Create New Documentation
- [ ] nmstate
     - https://github.com/coreos/fedora-coreos-config/pull/2269
     - @sumantro93
 - [ ] Installing FCOS on Azure Stack under Provisioning section 
 - [ ] Installing FCOS on s390x
     - virtual install
     - bare metal
     - IBM Cloud
 - [ ] Installing FCOS on Azure aarch64
     - Track for F39

## New test cases

- [ ] [nmstate](https://github.com/coreos/fedora-coreos-config/pull/2269)
    - @sumantro93
- [ ] provisioning on Azure Stack (requires new docs from above list)
    - @mike-nguyen
- [ ] provisioning on Nutanix (requires new docs from above list)
    - who?
- [x] provisioning on [Raspberry Pi 4 using U-Boot and EDK2](https://docs.fedoraproject.org/en-US/fedora-coreos/provisioning-raspberry-pi4/)
    - @dustymabe
- [ ] [enabling autologin and custom hostname tutorial](https://docs.fedoraproject.org/en-US/fedora-coreos/tutorial-autologin/)
    - @sumantro93
- [ ] [starting a service on first boot tutorial](https://docs.fedoraproject.org/en-US/fedora-coreos/tutorial-services/)
    - @sumantro93
- [ ] [SSH access and starting containers tutorial](https://docs.fedoraproject.org/en-US/fedora-coreos/tutorial-containers/)
    - @sumantro93
- [ ] [Launching a user-level systemd unit on boot tutorial](https://docs.fedoraproject.org/en-US/fedora-coreos/tutorial-user-systemd-unit-on-boot/)
    - @sumantro93
- [ ] [Testing FCOS updates tutorial](https://docs.fedoraproject.org/en-US/fedora-coreos/tutorial-updates/)
    - @sumantro93
- [ ] Add new table for s390x testing
    - should have test cases for virtual install, bare metal and IBMCloud
        - @sumantro93

**Comment by sumantro93** [comment]
@dustymabe  I have written up https://fedoraproject.org/wiki/QA:Testcase_nmstate , please review and I will add it to the test day app.

**Comment by sumantro93** [comment]
Autologin TC https://fedoraproject.org/wiki/QA:Testcase_FCOS_autologin_setting_custom_hostname

**Comment by sumantro93** [comment]
Systemd unit service : https://fedoraproject.org/wiki/QA:Testcase_FCOS_systemd_unit_service

**Comment by dustymabe** [comment]
> @dustymabe I have written up https://fedoraproject.org/wiki/QA:Testcase_nmstate , please review and I will add it to the test day app.

This looks like it's a generic `nmstate` test to be executed on any variant of Fedora. This is fine for now, but I think ideally what we should have is a docs entry in our FCOS docs for `nmstate` and make our test case use the Ignition workflow to use `nmstate` to configure networking for a system.



> Autologin TC https://fedoraproject.org/wiki/QA:Testcase_FCOS_autologin_setting_custom_hostname

Can we put these under the tutorials section on the test day page? Also maybe we can rename it with tutorial in the name?

> Systemd unit service : https://fedoraproject.org/wiki/QA:Testcase_FCOS_systemd_unit_service

I think I'd be more comfortable with this test case if it just linked to the tutorial. Really what we are doing here is not really making sure systemd works (we have plenty of automated tests for that already), but rather making sure our tutorials aren't stale. From the description of this issue each of those checklist items are to test the different tutorial guides.

**Comment by dustymabe** [comment]
I added a Raspberry Pi 4 test case: https://fedoraproject.org/wiki/QA:Testcase_CoreOS_Raspberry_Pi

**Comment by dustymabe** [comment]
>  - [ ] Installing FCOS on s390x
>    - virtual install
>    - bare metal
>    - IBM Cloud

@sumantro93 can you add a table for s390x to the test day event page?

**Comment by sumantro93** [comment]
I am adding the table now.
and I will be taking all the suggestions into account

**Comment by nikita-dubrovskii** [comment]
> > * [ ]  Installing FCOS on s390x
> >   
> >   * virtual install
> >   * bare metal
> 

Just as a note here: did test (installtion + `cosa kola ...`) 2 scenarios mentioned above: 
- zKVM, SeceureExecution (`fedora-coreos-38.20230323.dev.0-qemu.s390x.qcow2` , `fedora-coreos-38.20230323.dev.0-qemu-secex.s390x.qcow2`)
- zVM (`fedora-coreos-38.20230323.dev.0-live-[kernel|initramfs|rootfs]`)

FCOS was built locally on z15 machine

**Comment by bgilbert** [comment]
Should we close this out?
