### ISSUE TITLE
tracker: Rebase onto Fedora 39

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#1490]
# Rebase to a new version of Fedora (N=39)

### Open tickets to track related work for this release

- [x] Fedora Changes Considerations ([example](https://github.com/coreos/fedora-coreos-tracker/issues/1222)) 👉 https://github.com/coreos/fedora-coreos-tracker/issues/1491
- [x] Package Additions/Removals ([example](https://github.com/coreos/fedora-coreos-tracker/issues/1221)) 
- [x] Test Week ([template](https://github.com/coreos/fedora-coreos-tracker/issues/new?template=test-week.md&title=tracker:+FN+Test+Week))
- [x] Fedora N Release Communications ([example](https://github.com/coreos/fedora-coreos-tracker/issues/1503)) 👉 https://github.com/coreos/fedora-coreos-tracker/issues/1503

## At Branching

Branching is when a new stream is "branched" off of `rawhide`. This eventually becomes the next major Fedora (N).

### Release engineering changes

- [x] Verify that a few tags were created when branching occurred:

- `f${N+1}-coreos-signing-pending`
- `f${N+1}-coreos-continuous`

- [x] Add and tag a package (any package) which is in the stable repos into the continuous tag. This will create the initial yum repo that's used as input for building the COSA container.

- `koji add-pkg --owner ${FAS_USERNAME} f${N+1}-coreos-continuous $PKG`
    - example: `koji add-pkg --owner dustymabe f36-coreos-continuous fedora-release`
    - This example uses the [`fedora-release`](https://src.fedoraproject.org/rpms/fedora-release) RPM, but it could be any other.
- `koji tag-build f${N+1}-coreos-continuous $BUILD`
    - example: `koji tag-build f36-coreos-continuous fedora-release-36-0.16`

- [x] Add the N+1 signing key short hash (usually found [here](https://pagure.io/fedora-infra/ansible/blob/main/f/roles/bodhi2/backend/templates/pungi.rpm.conf.j2)) to the tag info for the coreos-pool tag. The following commands view the current settings and then update the list to the 32/33/34/35 keys. You'll most likely have to get someone from releng to run the second command (`edit-tag`).
    - `koji taginfo coreos-pool`
    - `koji edit-tag coreos-pool -x tag2distrepo.keys="12c944d0 9570ff31 45719a39 9867c58f"`

### coreos-installer changes

- [x] Update coreos-installer to know about the signing key used for the future new major version of Fedora (N+1).
- [x] Drop the signing key for the obsolete stable release (N-2).

### Update `rawhide` stream

- [x] Update [manifest.yaml](https://github.com/coreos/fedora-coreos-config/blob/rawhide/manifest.yaml) to list N+1 as the releasever.

### Enable `branched` stream

- [x] Update [manifest.yaml](https://github.com/coreos/fedora-coreos-config/blob/branched/manifest.yaml) to list N as the releasever.
- [x] Update [config.yaml](https://github.com/coreos/fedora-coreos-pipeline/blob/main/config.yaml) to un-comment out the `branched` stream definition.

### Update [fedora-coreos-config](https://github.com/coreos/fedora-coreos-config/) `next-devel`

- [x] Bump `releasever` in `manifest.yaml`
- [x] Update the repos in `manifest.yaml` if needed
- [x] Run `cosa fetch --dry-run --update-lockfile`
    - this updates the x86_64 lockfile - the others will get updated when `bump-lockfile` runs.
    - in the future we may support [this](https://github.com/coreos/coreos-assembler/issues/3088) in `cosa fetch` directly
- [x] PR the result

- [x] Re-enable `next-devel` if needed ([docs](https://github.com/coreos/fedora-coreos-pipeline/tree/main/next-devel))
- [x] Disable `branched` stream since it is no longer needed.
    - Update [config.yaml](https://github.com/coreos/fedora-coreos-pipeline/blob/main/config.yaml) to comment out the `branched` stream definition.

### Ship rebased `next`

- [x] Ship `next`
- [x] Set a new update barrier for the final release of N-1 on `next`. In the barrier entry set a link to [the docs](https://docs.fedoraproject.org/en-US/fedora-coreos/update-barrier-signing-keys/). See [discussion](https://github.com/coreos/fedora-coreos-tracker/issues/480#issuecomment-1247314065)

### Update [fedora-coreos-config](https://github.com/coreos/fedora-coreos-config/) `testing-devel`

- [x] Bump `releasever` in `manifest.yaml`
- [x] Update the repos in `manifest.yaml` if needed
- [x] Sync the lockfiles for all arches from `next-devel`
- [x] Bump the base Fedora version in `ci/buildroot/Dockerfile`
- [x] PR the result

### Ship rebased `testing`

- [x] Ship `testing`
- [x] Set a new update barrier for the final release of N-1 on `testing`. In the barrier entry set a link to [the docs](https://docs.fedoraproject.org/en-US/fedora-coreos/update-barrier-signing-keys/). See [discussion](https://github.com/coreos/fedora-coreos-tracker/issues/480#issuecomment-1247314065)

### Disable `next-devel` stream

We prefer to disable `next-devel` when there is no difference between `testing-devel` and `next-devel`. This allows us to prevent wasting a bunch of resources (bandwidth, storage, compute) for no reason. After the switch to N if `next-devel` and `testing-devel` are in lockstep, then disable `next-devel`.

- [x] Follow the instructions [here](https://github.com/coreos/fedora-coreos-pipeline/tree/main/next-devel) to disable `next-devel`

### Switch upstream packages to shipping release binaries from Fedora (N)

- [x] Update [repo-templates](https://github.com/coreos/repo-templates) [config.yaml](https://github.com/coreos/repo-templates/blob/main/config.yaml) with the version number and GPG key ID for Fedora (N).

### Disable the `fedora-candidate-compose` repo

- [x] Remove from the `manifest.yaml` of `next-devel` the `fedora-candidate-compose` repo

### Ship rebased `stable`

- [x] Ship `stable`
- [x] Set a new update barrier for the final release of N-1 on `stable`. In the barrier entry set a link to [the docs](https://docs.fedoraproject.org/en-US/fedora-coreos/update-barrier-signing-keys/). See [discussion](https://github.com/coreos/fedora-coreos-tracker/issues/480#issuecomment-1247314065)

### Untag old packages

`koji untag` N-2 packages from the pool (at some point we'll have GC in place to do this for us, but for now we must remember to do this manually or otherwise distRepo will fail once the signed packages are GC'ed). For example the following snippet finds all RPMs signed by the Fedora 32 key and untags them. Use this process:

- [x] Find the key short hash. Usually found [here](https://pagure.io/fedora-infra/ansible/blob/main/f/roles/bodhi2/backend/templates/pungi.rpm.conf.j2). Then:

```
f32key=12c944d0
key=$f32key
echo > untaglist # create or empty out file
for build in $(koji list-tagged --quiet coreos-pool | cut -f1 -d' '); do
    if koji buildinfo $build | grep $key 1>/dev/null; then
        echo "Adding $build to untag list"
        echo "${build}" >> untaglist
    fi
done
```

Now we have a list of builds to untag. But we need a few more sanity checks.

- [x] Make sure none of the builds are used in `N` based FCOS. Check by running:

```
f32key=12c944d0
key=$f32key
podman run -it --rm quay.io/fedora/fedora-coreos:testing-devel rpm -qai | grep -B 9 $key
podman rmi quay.io/fedora/fedora-coreos:testing-devel
```

If there are any RPMs signed by the old key they'll need to be investigated. Maybe they shouldn't be used any longer. Or maybe they're still needed.

- [x] For any RPMS still used by `N-1` based FCOS let's remove them from the untaglist. Check by running:

```
f32key=12c944d0
key=$f32key
podman run -it --rm quay.io/fedora/fedora-coreos:stable rpm -qai | grep -B 9 $key
podman rmi quay.io/fedora/fedora-coreos:stable
```

NOTE: This assumes `stable` is still on `N-1`.

Remove any entries from the `untaglist` file that are still being used.

- [x] After verifying the list looks good, untag:

```
# use xargs so we don't exhaust bash string limit
cat untaglist | xargs -L50 koji untag-build coreos-pool
```

- [x] Now that untagging is done, give a heads up to rpm-ostree developers that N-2 packages have been untagged and that they may need to update their CI compose tests to freeze on a newer FCOS commit.

- [x] Remove the N-2 signing key from the tag info for the coreos-pool tag. The following commands view the current settings and then update the list to the 33/34/35 keys. You'll most likely have to get someone from releng to run the second command (`edit-tag`).
    - `koji taginfo coreos-pool`
    - `koji edit-tag coreos-pool -x tag2distrepo.keys="9570ff31 45719a39 9867c58f"`

### Open ticket for the next Fedora rebase

- [x] Create a new ticket from the [rebase template](https://github.com/coreos/fedora-coreos-tracker/issues/new?assignees=&labels=area%2Fplatforms%2C+kind%2Fenhancement&template=rebase.md&title=tracker:+Rebase+onto+Fedora+N)
    - label with `FN` label where `N` is the Fedora version.

## Miscellaneous container updates

These are various containers in use throughout our ecosystem. We should update or open a ticket to track updating them once a new Fedora release is out. If you open a ticket instead of doing the update add a link to the ticket as comment.

- [x] Update coreos-assembler or open ticket to update:
    - [Dockerfile](https://github.com/coreos/coreos-assembler/blob/main/Dockerfile)
- [x] Update coreos-installer
    - [Dockerfile](https://github.com/coreos/coreos-installer/blob/main/Dockerfile)
- [x] Update Ignition
    - [Dockerfile.validate](https://github.com/coreos/ignition/blob/main/Dockerfile.validate)
- [x] Update Butane
    - [Dockerfile](https://github.com/coreos/butane/blob/main/Dockerfile)
- [x] Update fedora-coreos-cincinnati
    - [Dockerfile](https://github.com/coreos/fedora-coreos-cincinnati/blob/main/dist/fedora-infra/Dockerfile)
- [x] Update config-bot
    - [Dockerfile](https://github.com/coreos/fedora-coreos-releng-automation/blob/main/config-bot/Dockerfile)
- [x] Update coreos-koji-tagger
    - [Dockerfile](https://github.com/coreos/fedora-coreos-releng-automation/blob/main/coreos-koji-tagger/Dockerfile)
    - [ImageStream](https://pagure.io/fedora-infra/ansible/blob/main/f/roles/openshift-apps/coreos-koji-tagger/templates/imagestream.yml)
    - [BuildConfig](https://pagure.io/fedora-infra/ansible/blob/main/f/roles/openshift-apps/coreos-koji-tagger/templates/buildconfig.yml)
- [x] Update coreos-ostree-importer
    - [Dockerfile](https://github.com/coreos/fedora-coreos-releng-automation/blob/main/coreos-ostree-importer/Dockerfile)
    - [ImageStream](https://pagure.io/fedora-infra/ansible/blob/main/f/roles/openshift-apps/coreos-ostree-importer/templates/imagestream.yml)
    - [BuildConfig](https://pagure.io/fedora-infra/ansible/blob/main/f/roles/openshift-apps/coreos-ostree-importer/templates/buildconfig.yml)

**Comment by aaradhak** [comment]
- https://github.com/coreos/coreos-installer/pull/1264

**Comment by aaradhak** [comment]
- https://github.com/coreos/fedora-coreos-config/pull/2548

**Comment by aaradhak** [comment]
- https://github.com/coreos/fedora-coreos-pipeline/pull/904

**Comment by dustymabe** [comment]
- https://github.com/coreos/fedora-coreos-pipeline/pull/908
- https://github.com/coreos/fedora-coreos-config/pull/2592

**Comment by dustymabe** [comment]
As we have done in the past we will be fast-tracking packages in `next-devel`/`next` to ensure no upgrade transition will ever include downgraded packages.

**Comment by dustymabe** [comment]
- first `next` release on F39:
    - https://github.com/coreos/fedora-coreos-streams/issues/767
- PR with barrier set for last f38 next stream release:
    - https://github.com/coreos/fedora-coreos-streams/pull/768

**Comment by dustymabe** [comment]
PR to promote last `next` to `testing`:

- https://github.com/coreos/fedora-coreos-config/pull/2710

PR to add a barrier for the last F38 `testing` release:

- https://github.com/coreos/fedora-coreos-streams/pull/801

**Comment by dustymabe** [comment]
In `38.20231027.2.0` it was the last 38 release of `testing`. it also happens to be the first release with the [zincati problem](https://github.com/coreos/fedora-coreos-tracker/issues/1608). To avoid this problem we'll make the 38->39 update barrier (the one that satisfies https://docs.fedoraproject.org/en-US/fedora-coreos/update-barrier-signing-keys/) be `38.20231014.2.0` rather than `38.20231027.2.0`.

**Comment by dustymabe** [comment]
disabled `next-devel` in https://github.com/coreos/fedora-coreos-pipeline/pull/945

shipped rebased stable in https://github.com/coreos/fedora-coreos-streams/pull/822

**Comment by dustymabe** [comment]
- https://github.com/coreos/repo-templates/pull/198

**Comment by dustymabe** [comment]
- https://github.com/coreos/fedora-coreos-config/pull/2813

**Comment by travier** [comment]
Prepared a part of "Update fedora-coreos-cincinnati" earlier but forgot to link it here: https://github.com/coreos/fedora-coreos-cincinnati/pull/95 (the follow-up steps are linked from the PR).

**Comment by c4rt0** [comment]
Miscellaneous container updates:
coreos-assembler [Dockerfile](https://github.com/coreos/coreos-assembler/blob/main/Dockerfile#L3) already using F39 ✅

**Comment by c4rt0** [comment]
[Coreos-koji-tagger/imagestream PR](https://pagure.io/fedora-infra/ansible/pull-request/1765)
