### ISSUE TITLE
F39 FCOS Test Day TODO List

### ISSUE THREAD

**Issue by ravanelli** [coreos/fedora-coreos-tracker#1571]
## Existing test cases

 * https://testdays.fedoraproject.org/events/159

## Create New Documentation
 - [ ] nmstate
     - https://github.com/coreos/fedora-coreos-config/pull/2269
     -  [Test case ](https://fedoraproject.org/wiki/QA:Testcase_nmstate)
     - See comment https://github.com/coreos/fedora-coreos-tracker/issues/1445#issuecomment-1486189920
 - [ ] Installing FCOS on Azure Stack under Provisioning section 
 - [ ] Installing FCOS on s390x
     - virtual install
     - bare metal
     - IBM Cloud
 - [ ] Installing FCOS on Azure aarch64
     - Track for F39
 
 ## Change Test Wiki
 - [x] Change Tutorial links :
 We want one test to point to the top [level ](https://docs.fedoraproject.org/en-US/fedora-coreos/tutorial-setup/) so people may try to run all tests and point each one they stopped or had issues.
  - [x] New platforms:
        - ppc64le
        - hyper-v  (Add it as part of Cloud launch)
        - kubevirt
  - [x] Change Cloud launch to Platforms launch
  - [x]  Add entry for aarch64 gcp
  - [x]  Add entry for Clouds: Nutanix 
  - [x]  Fix s90x to s390x
  
 
## New test cases
- [x] provisioning on kubevirt 
- [x] provisioning on hyper-v 
- [ ] provisioning on Azure Stack (requires new docs from above list)
- [x] provisioning on Nutanix (requires new docs from above list)

**Comment by ravanelli** [comment]
@sumantro93 Are you able to help us with the wiki updates needed? Or is it possible for me to have access on it?

**Comment by travier** [comment]
Which one is you Fedora account? I can see both https://accounts.fedoraproject.org/user/ravanelli/ and https://accounts.fedoraproject.org/user/rravanel/. You should be able to edit the wiki once you are part of at lest one group and the first one is so it should work with it.

**Comment by ravanelli** [comment]
@travier I said wiki, but I mean https://testdays.fedoraproject.org/events/159. I think we don't have access to it right?

**Comment by travier** [comment]
This page I don't have access. Not sure if we can edit things there.

**Comment by ravanelli** [comment]
Here is how we edit it:

Edit: https://fedoraproject.org/wiki/Test_Day:Fedora_39_CoreOS_Test_Day_TestdayApp_Metadata. 

Pass the URL to https://testdays.fedoraproject.org/admin/add_event
And itt will update the contents of 159 event.
