### ISSUE TITLE
Container Linux migration documentation

### ISSUE THREAD

**Issue by bgilbert** [coreos/fedora-coreos-tracker#159]
Spun out from #48.

The Container Linux distro currently has a planned EOL in 2020, and users will need to migrate to Fedora CoreOS to remain supported.  We'll need to document the differences to make the migration as painless as possible.

This bug tracks known differences that need to be documented.

## Installation
- [x] `coreos-install` -> `coreos-installer`
- [x] Autologin kernel command-line parameter (#112)
- [ ] Migrating from [CL image types](https://alpha.release.core-os.net/amd64-usr/current/) to FCOS ones
- [x] Vagrant images (#144)

## User configuration
- [ ] Ignition config spec changes
- [ ] Availability of users/groups in Ignition configs (#155)
- [ ] CLC -> FCC changes
- [ ] coreos-metadata rename: systemd services and provider variable, metadata path and variables
- [x] PXE custom OEMs
- [ ] `/etc` path differences
- [x] ntpd/systemd-timesyncd -> chronyd
- [x] etcd
- [x] flannel
- [x] locksmith (#3)
- [x] networkd (#24)
- [x] Password login (#138)
- [x] Docker version selection
- [ ] Docker configuration differences (#2, etc.)
- [ ] Immutable root directory (#270)

## Operator notes
- [ ] Release streams and recommendations for production
- [x] update-ssh-keys (#139)
- [ ] Update system and commands
- [x] SELinux policy differences
- [ ] toolbox differences (#38)
- [ ] Custom kernel modules (#15)
- [ ] ostree, `/etc`, and `/var`
- [x] Metrics (#86)
- [ ] Automatic rollback mechanism differences
- [x] Cloud CLI clients (#75)
- [x] Different behavior when opening an existing file in a sticky directory (https://github.com/coreos/bugs/issues/2577)
- [x] SMT disablement (#181)

## Implementation notes
- [ ] Partition layout differences
- [x] sshd socket activation
- [x] Default filesystems (#33)
- [x] OEM partition support
- [ ] Automatic filesystem resizing differences (#45)

**Comment by dhawal55** [comment]
Is [torcx](https://github.com/coreos/torcx) still going to be the tool of choice for boot-time configuration? Should we add torcx to the above list?

**Comment by bgilbert** [comment]
@dhawal55 Nope, it's not.

**Comment by bgilbert** [comment]
At this point I think it's unlikely that further work will be done here, so I propose closing this out.

**Comment by bgilbert** [comment]
Closing per https://github.com/coreos/fedora-coreos-tracker/issues/159#issuecomment-824476821.
