### ISSUE TITLE
F40 FCOS Test Day TODO List

### ISSUE THREAD

**Issue by aaradhak** [coreos/fedora-coreos-tracker#1686]
## Create New Documentation

- [x] iSCSI
    - Subsection in https://docs.fedoraproject.org/en-US/fedora-coreos/bare-metal/ ?
    - https://github.com/coreos/fedora-coreos-docs/pull/618
- [x] Hyper-V
    - documented at https://docs.fedoraproject.org/en-US/fedora-coreos/provisioning-hyperv/
- [ ] Apple Hypervisor
    - would be nice but lower priority since it's covered by podman too

### These are carried over from the last test day

 - [ ] nmstate
     - https://github.com/coreos/fedora-coreos-config/pull/2269
     - [Test case ](https://fedoraproject.org/wiki/QA:Testcase_nmstate)
     - See comment https://github.com/coreos/fedora-coreos-tracker/issues/1445#issuecomment-1486189920
     - docs PR: https://github.com/coreos/fedora-coreos-docs/pull/536
 - [ ] Installing FCOS on Azure Stack under Provisioning section 
 - [ ] Installing FCOS on s390x
     - virtual install
     - bare metal
 - [ ] Installing FCOS on Azure aarch64
     - Track for F39

## Create New Test Cases

- [x] Hyper-V
- [ ] iSCSI
- [x] Podman v5 migration (should be shareable with Podman test week)
- [ ] Provisioning on Azure Stack (requires new docs from above list)
