### ISSUE TITLE
tracker: F41 Test Week on Oct 7

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#1801]
## Initial Tasks (to be done at least one week before test week)

- [x] Open this ticket in the `fedora-coreos-tracker` repo
- [x] Open a ticket with [Fedora QA](https://pagure.io/fedora-qa/issues).
  - [F36 example](https://pagure.io/fedora-qa/issue/695)

To be done after the Fedora QA folks have taken action on the QA ticket:

- [x] Confirm the Test Day page is created on the Fedora Wiki.
  - For example: <https://fedoraproject.org/wiki/Test_Day:Fedora_36_CoreOS_2022-04-04>
- [x] Confirm the Test Day results app is created.
  - For example: <https://testdays.fedoraproject.org/events/131>
- [x] Choose a day during the Test Week to host a video session for live debug help
- [x] Setup a Google Meet or other video conference session
- [x] Create a HackMD doc for capturing notes during live video session
- [x] Find volunteers to enumerate new documentation + test cases required for Test Week
  - Best done via dedicated video session
- [x] File an issue on `fedora-coreos-tracker` with TODO items.
  - <https://github.com/coreos/fedora-coreos-tracker/issues/1807>
- [x] Ask @ravanelli to give the test users the badge
  

## Announcing Test Week

Should be completed after the Initial Tasks are done

- [x] Draft an email to <coreos@lists.fedoraproject.org> announcing the Test Week
  - [x] Include a link to the Fedora Wiki
  - [x] Include a link to the Test Day results app
  - [x] Include a link to `fedora-coreos-tracker` for Test Week
  - [x] Include a link to the video conference
  - [x] Include a link to the HackMD doc
- [x] Cross-post announcement email to discussion.fedoraproject.org with `#coreos` tag

- Example format: <https://hackmd.io/lCrVoW_RSMCRf2neiGhiPg>

## During Test Week

- Monitor `fedora-coreos-tracker` for new issues reported as part of Test Week
- Monitor #fedora-coreos on IRC for new issues reported as part of Test Week
- Ensure there is one or more representatives of Fedora CoreOS team present for live video session

## After Test Week

- [x] Update `fedora-coreos-tracker` ticket with any issues found
- [x] Update `fedora-coreos-tracker` ticket with any documentation updates made
- [x] Review Test Day results app and follow-up on any errors reported, if possible
- [x] Follow up with @ravanelli  the Fedora Badges with Fedora Account System (FAS) usernames that participated in Test Week

**Comment by gursewak1997** [comment]
Fedora QA Ticket: https://pagure.io/fedora-qa/issue/790

**Comment by sumantro93** [comment]
wiki : https://fedoraproject.org/wiki/Test_Day:Fedora_41_CoreOS
results : https://testdays.fedoraproject.org/events/198
Fedocal : https://calendar.fedoraproject.org/QA/2024/10/7/#m10901

I will also be doing relevant communication on test list and fedora magazine

Please lemme know if we need more testing scenarios or cases that need additions!

**Comment by sumantro93** [comment]
Hey, is the announcement email sent out already? I might have missed it. Can someone please give me the archive link?

**Comment by gursewak1997** [comment]
> Hey, is the announcement email sent out already? I might have missed it. Can someone please give me the archive link?

https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/TIECUJDI47R6FR4ABBBVWXMBCAXJGOV4/
