### ISSUE TITLE
s390x: TODO

### ISSUE THREAD

**Issue by tuan-hoang1** [coreos/fedora-coreos-tracker#255]
Hi, I would like to make this issue as a main tracker for all s390x-related issues and pull requests, both for FCOS and RHCOS branches. Feel free to update/change to match current status of development.

### FCOS
- [x] cosa deps
https://github.com/coreos/coreos-assembler/pull/694
- [x] cosa QEMU devices
https://github.com/coreos/coreos-assembler/pull/700
- [x] cosa without anaconda
https://github.com/coreos/coreos-assembler/pull/701
- [x] cosa deps s390x
https://github.com/coreos/coreos-assembler/pull/702
- [x] dealing with grub configs and efi
https://github.com/coreos/coreos-assembler/pull/706
- [x] bootloader: minimal zipl.conf file
https://github.com/ibm-s390-tools/s390-tools/pull/71
- [x] bootloader: large number of BLS files
https://github.com/ibm-s390-tools/s390-tools/pull/73
- [x] bootloader: prefix for `initrd` and `kernel` fields in BLS files
https://github.com/ibm-s390-tools/s390-tools/pull/74
- [x] bootloader: ostree backend for zipl
https://github.com/ostreedev/ostree/pull/1937
- [x] bootloader: error with same 'title' fileds
https://github.com/ostreedev/ostree/pull/1911
- [x] bootloader: blank lines issue
Fixed in s390-tools: https://github.com/ibm-s390-tools/s390-tools/pull/62
Fixed in ostree: https://github.com/ostreedev/ostree/pull/1904
- [x] bootloader: order of BLS fields
**Opening** in s390-tools: https://github.com/ibm-s390-tools/s390-tools/issues/64
Fixed in ostree: https://github.com/ostreedev/ostree/pull/1904
- [x] rpm-ostree
https://github.com/projectatomic/rpm-ostree/issues/1885
https://github.com/projectatomic/rpm-ostree/pull/1886
- [x] cosa build installer
https://github.com/coreos/coreos-assembler/pull/716
https://github.com/coreos/fedora-coreos-config/pull/146
- [x] label, partlabel - there is an endian bug in gptfdisk
https://github.com/coreos/ignition-dracut/pull/100
- [ ] Ignition: z/VM hypervisor support
https://github.com/coreos/ignition/pull/865
https://github.com/coreos/ignition-dracut/pull/118
- [ ] cosa build installer - part 2
https://github.com/coreos/coreos-assembler/pull/732/
- [x] **KVM: Passing ignition file to guest** - temporary solution using guestfish
https://github.com/coreos/mantle/issues/1045
https://github.com/coreos/mantle/pull/1050
https://github.com/coreos/ignition-dracut/pull/49
- [ ] **KVM: Passing ignition file to guest**
https://github.com/coreos/ignition/issues/825
- [x] mantle + kola
https://github.com/coreos/mantle/pull/1048
https://github.com/coreos/coreos-assembler/pull/724
- [x] mantle netlink issue
https://github.com/coreos/mantle/issues/1044
https://github.com/coreos/mantle/pull/1049
- [x] bare metal image - zFCP SCSIs
https://github.com/coreos/coreos-assembler/pull/733
- [ ] z/VM + LPAR: zFCP SCSI disks
https://github.com/coreos/coreos-installer/pull/61
- [ ] z/VM + LPAR: ECKD DASD disks 
https://github.com/coreos/coreos-installer/pull/61
https://github.com/coreos/coreos-assembler/pull/779
- [ ] bootloader: ignition-firstboot-complete
https://github.com/coreos/ignition-dracut/pull/117
- [x] bootloader: keep firstboot parameters ephemeral
https://github.com/coreos/coreos-assembler/pull/780
- [x] BLS: persisting dasd/zfcp/qeth parameters after second boot
https://github.com/coreos/fedora-coreos-tracker/issues/305
- [ ] automatic rollback
https://github.com/coreos/ignition-dracut/issues/84
- [ ] bootloader: general tracker for bootloader issue
https://github.com/ostreedev/ostree/issues/1888
- [ ] coreos-installer Live ISO
WIP

### RHCOS only
- [x] Anaconda patch to support zipl in rpmostree-payload case
https://bugzilla.redhat.com/show_bug.cgi?id=1741908
- [x] check if /boot/efi is present
https://github.com/coreos/coreos-assembler/pull/705
- [x] Backport effort part 1
https://github.com/coreos/coreos-assembler/pull/772
https://github.com/coreos/coreos-assembler/pull/782

### Incoming PRs and TODOs for FCOS:
- DHCP vs static IP assignment discussion for coreos-installer

### Incoming PRs and TODOs for RHCOS:
- backport z/VM LPAR patches
- backport ostree patches
- backport s390-tools patches

### Long term work FCOS & RHCOS:
- Automatic rollback. See ignition-dracut#84 above.

**Comment by dustymabe** [comment]
Thanks for creating this issue. I think it really helps map the work and the progress.

**Comment by lucab** [comment]
Just to confirm: is the `basearch` for this port `s390x` (i.e. with the trailing "x")?

**Comment by alicefr** [comment]
@lucab yes, with "x".
@tuan-hoang1 can you add this issue for rpm-ostree at the list https://github.com/projectatomic/rpm-ostree/issues/1885

**Comment by ajeddeloh** [comment]
This appears to only track the short term work (i.e. get it working without anaconda) and not the long term (i.e. use zipl to load grub2-emu) work. Can we break out that into this list as well?

**Comment by tuan-hoang1** [comment]
I believe we want to track everything short and long terms. For example for grub2-emu, I put it as `automatic rollback` above.
