### ISSUE TITLE
tracker for 'no cloud agents' work

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#95]
- [ ] no cloud agents: azure #65
- [ ] no cloud agents: aws #66
- [ ] no cloud agents: gce #67
- [ ] no cloud agents: openstack #68
- [ ] no cloud agents: packet #69 
- [ ] no cloud agents: vmware #70
- [ ] no cloud agents: digitalocean #71
- [ ] no cloud agents: virtualbox #73
- [ ] no cloud agents: qemu #74

**Comment by bgilbert** [comment]
What is the criterion for checking off a platform?
- Having a plan?
- Implementing the necessary pieces?
- Producing build artifacts for that platform?
- Having the pipeline upload images to that platform?

**Comment by dustymabe** [comment]
> What is the criterion for checking off a platform?

added sub checkboxes

**Comment by Aketzu** [comment]
I would like to have check for Xen (and specifically paid XenServer). 
There is no general cloud-init support so installation is manual. With Atomic I added custom Kickstart URL which then downloaded xe-guest-utilities and queried VM name through xen interface.

**Comment by bgilbert** [comment]
@Aketzu Xen isn't currently in our list of target platforms, but it's worth discussing further.  Could you open a new bug?

**Comment by dlabreu** [comment]
As a user of the oVIrt Project and Red Hat Virtualization, I find of great value have the guest agent on the Virtual machines, so I can sort to information right from the Engine Dashboard such as mentioned in here (Link) https://www.ovirt.org/develop/internal/guest-agent/guest-agent.html
Some of the enterprises still run workloads on top of on-prem virtualization tools and as a hybrid approach I am certain that have the guest agents on the virtuals would add value instead of subtracting it.

If the decision is to ship without the agents I assume a good compromise would be to provide a very simple way to inject the agents on the virtual machines and also provided the project with nice documentation about. I am new to it but would be more than happy to work on the doc for the oVirt guest agent as I am a user of the technology.
